// src/common/enums/permission.enum.ts
export enum Permission {
  // Управление пользователями
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  
  // Управление заявками
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  APPLICATION_APPROVE = 'APPLICATION_APPROVE',
  APPLICATION_REJECT = 'APPLICATION_REJECT',
  APPLICATION_READ = 'APPLICATION_READ',
  
  // Администрирование
  SYSTEM_MANAGE = 'SYSTEM_MANAGE',
  PERMISSION_MANAGE = 'PERMISSION_MANAGE',
  
  // Данные
  STUDENT_DATA_READ = 'STUDENT_DATA_READ',
  STUDENT_DATA_WRITE = 'STUDENT_DATA_WRITE',
  TEACHER_DATA_READ = 'TEACHER_DATA_READ',
  TEACHER_DATA_WRITE = 'TEACHER_DATA_WRITE',
  
  // Академические
  GRADE_MANAGE = 'GRADE_MANAGE',
  ATTENDANCE_MANAGE = 'ATTENDANCE_MANAGE',
  SCHEDULE_MANAGE = 'SCHEDULE_MANAGE',
  CONTRACT_MANAGE = 'CONTRACT_MANAGE'
}